name: Swift

on:
  push:
    branches: [ "master","TestBuild" ]
  pull_request:
    branches: [ "master" ]
env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Force Xcode
        run: sudo xcode-select -s "/Applications/Xcode.app"
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
